### ISSUE TITLE
Add Permissions Filter module

### ISSUE THREAD

**Issue by CNDexter** [kanopi/drupal-starter#103]
https://www.drupal.org/project/permissions_filter 

Most of the permissions pages are too large to scroll through and find what you want easily. This makes it a ton easier.

![Screenshot 2023-04-04 at 11-20-31 Permissions SFO Connect](https://user-images.githubusercontent.com/3587944/229840018-e520090c-bac6-4066-ba4b-fca50f264513.png)

**Comment by thejimbirch** [comment]
Merged your PR, thanks @CNDexter !
