### ISSUE TITLE
Use imagemagick for image process instead of using GD2 image manipulation toolkit

### ISSUE THREAD

**Issue by asipple1** [kanopi/drupal-starter#125]
Noticed images come out blurry using GD2 image manipulation toolkit. When using imagemagick the image do not.

**Comment by thejimbirch** [comment]
Lets make this a recipe in itself that could be called from drupal-build-starter, but also could be used retroactively on existing sites.

**Comment by thejimbirch** [comment]
[kanopi/imagemagick-configuration](https://packagist.org/packages/kanopi/imagemagick-configuration) recipe was created for this.
