### ISSUE TITLE
Include config for Administrator role in config instead of recipe

### ISSUE THREAD

**Issue by banoodle** [kanopi/drupal-starter#126]
The first time a developer runs fin init, it fails because the administrator role does not exist.

We currently configure the administrator role in the drupal-build-starter recipe.

Proposed change:

- Add role configuration to config
- Remove role configuration from recipe

**Comment by banoodle** [comment]
@thejimbirch I'm happy to queue up a PR with this fix if this proposal sounds OK with you.

**Comment by thejimbirch** [comment]
If you are running this for the first time, lets add notes to the readme about the 2 failures, cypress users and fin drush uli.

**Comment by thejimbirch** [comment]
We discussed this, and to add more clarity, these failures happen on setup. We should add notes about the failures in the readme.

**Comment by thejimbirch** [comment]
The Administrator role is now added in 

https://github.com/kanopi/saplings-editorial
