### ISSUE TITLE
Docksal init fails on line 109 because user 2 doesn't exist

### ISSUE THREAD

**Issue by banoodle** [kanopi/drupal-starter#131]
When developer runs fin init, the process fails when it gets to line 109 because it tries to access user 2 which does not exist.

I think the easies fix is to just change it to user 1.

**Comment by thejimbirch** [comment]
We discussed this also. This happens on initial setup only.

The installation documentation should state to add a User 2, and make that user an admin, and then block user 1 for security reasons.

Once this happens, the drush uli command will not fail.

**Comment by thejimbirch** [comment]
Making a note.  We don't have docs yet that tell us to block user 1.  Those need to be added.

**Comment by thejimbirch** [comment]
This is being worked on in drupal-starter-installer (private)
