### ISSUE TITLE
Upgrade Docksal version to support php 8.2

### ISSUE THREAD

**Issue by thejimbirch** [kanopi/drupal-starter#173]
But which?

https://docs.docksal.io/stack/images-versions/#cli

Says the latest is `docksal/cli:php8.1-3.3`

But https://github.com/docksal/service-cli/releases says these are available:

```
docksal/cli:php8.1-3.7
docksal/cli:php8.2-3.7
docksal/cli:php8.3-3.7
```

CircleCI and Pantheon are already at 8.2 and 10.6

**Comment by paulsheldrake** [comment]
Just `docksal/cli:php8.2` will work

**Comment by thejimbirch** [comment]
@paulsheldrake Requested your review on #174
