### ISSUE TITLE
Quicksilver pushback error: Unable to load Git token from secrets file

### ISSUE THREAD

**Issue by banoodle** [kanopi/drupal-starter#52]
On the explo project (which I based off of drupal-starter), we are seeing this error on the Pantheon Dashboard following a merge commit:

**Unable to load Git token from secrets file
Quicksilver Pushback: Error**

Looking at push-back.php, it appears the problem is it is looking for this file: "$privateFiles/.build-secrets/tokens.json", but it does not exist on the explo dev site. In fact I don't see the .build-secrets directory when I sftp into the Dev server and check in files/private.

I don't understand why the expected file is missing: whether that is something we are supposed to set up manually vs something the deployment scripts/webhooks are supposed to do?

I'm hoping Sean or Paul can advise/help with this one.

**Comment by sean-e-dietrich** [comment]
There is a step on one of the deploy scripts that sets the GITHUB_TOKEN and pushes the secrete to the remote we should make sure this is happening

**Comment by banoodle** [comment]
Thanks, @sean-e-dietrich. I don't see anywhere in web/private/scripts where we are setting the token.

I found this interesting info in the quicksilver readme just now...

![Screen Shot 2021-09-20 at 4 41 33 PM](https://user-images.githubusercontent.com/7685811/134091034-56dded3c-74e2-4641-8629-037453323547.png)

So for exploratorium, I just moved and renamed the json file as indicated. I think that will fix the issue as that is where pushback is expecting to find the token. The thing they mention about build-providers.json puzzles me - do you know where I would get this file from? We don't see to have it. Not sure if it's critically important or not.

**Comment by banoodle** [comment]
ignore my question about build-providers.json. I now see it in the project root.

**Comment by paulsheldrake** [comment]
We should remove the quicksilver pushback functionality.  We're the only
people working on the project and everything goes through GitHub

**Comment by thejimbirch** [comment]
It has been removed from this repository.  We should remove from repo's that used this as a starter.  Leaving this issue open.

**Comment by thejimbirch** [comment]
Closing as won't do.  Individual projects don't seem to be complaining about it.
