### ISSUE TITLE
Document fin share

### ISSUE THREAD

**Issue by thejimbirch** [kanopi/drupal-starter#6]
The command `fin share` implements ngrok which creates public URLs for demoing from your own machine or viewing on mobile devices. 

Words should be added to the Readme about it.

https://ngrok.com/

**Comment by froboy** [comment]
@thejimbirch @sean-e-dietrich I'm wondering where the best place for this is? I converted [the `fin` section of the starter readme](https://github.com/kanopi/starter-8#easier-setup-with-fin-init) into a [listing of all the relevant `fin` commands for Benetech](https://github.com/kanopi/starter-8#easier-setup-with-fin-init). Would it make sense to bring some of that back into the main repo? Something like "fin is fun and cool and there're commands and stuff". Here are some useful ones and here're docs on how to make more." I can take a stab at that.

**Comment by sean-e-dietrich** [comment]
I honestly don't think we need to document this as it's already documented on the docksal docs https://docs.docksal.io/tools/ngrok/

**Comment by froboy** [comment]
Nice. Would it make sense to break out our docs as I described above to have some similar listings for all the custom commands?

**Comment by thejimbirch** [comment]
I like having the commands in the readme.  Linking to the Docksal docs is a good idea, but even then, I don't know that I would click on ngrok, it sounds like a weird planet on Star Trek that I don't know about.

PS, I also have a list of commands in [this projects readme](https://github.com/kanopi/corum)

**Comment by thejimbirch** [comment]
Documented in the list of commands in the Readme
