### ISSUE TITLE
scheduled_update_check jobs are failing on circleci

### ISSUE THREAD

**Issue by banoodle** [kanopi/drupal-starter#61]
In our Kanilla project, which I based on this starter, we are seeing these errors...

![Screen Shot 2021-11-03 at 11 33 36 AM](https://user-images.githubusercontent.com/7685811/140176945-af8ae069-6e49-48a3-9fc5-c57344002891.png)

Here are the details from one of these failed jobs...
![Screen Shot 2021-11-03 at 12 08 28 PM](https://user-images.githubusercontent.com/7685811/140176938-722a2d29-7bb3-4d3c-be8a-304ef59674a1.png)

It looks like we are missing some of the ingredients listed under Installation [here](https://github.com/danielbachhuber/composer-lock-updater), specifically the [hub](https://github.com/github/hub) CLI tool and its configuration. 

I think I could take a shot at submitting a PR for this, but I don't understand how to install the hub cli tool within circleci - is it just a matter of adding download steps to the circlci config.yml or would it be added to the orb itself?

**Comment by thejimbirch** [comment]
I believe this is from the outdated docker image.  I updated in https://github.com/kanopi/drupal-starter/pull/62 and added a PR to Kanilla.

Sean mentioned it in https://kanopi.slack.com/archives/C04CRR2UA/p1635354015094800

**Comment by thejimbirch** [comment]
This job was replaced with `automated-updates`.  Closing.
